bag_directory: "/tmp/rosbag_mpc_data_17/"
bag_name: "rosbag_mpc_data_17_0.db3"
dt_ocp: 0.01
mpc_freq: 100
nb_running_nodes: 60
endeff_name: "fer_hand_tcp"
robot_name: panda

# optional parameter
mpc_data_topic_name: "/ctrl_mpc_linearized/xu_solution"
T_sim: 20
mpc_solve_time_topic_name: "/ctrl_mpc_linearized/ocp_solve_time"
